# Generated by Django 3.1.5 on 2021-01-29 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorys', to='magaz.category')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Subsubcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylar', to='magaz.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorylar', to='magaz.subcategory')),
            ],
            options={
                'verbose_name': 'Под подкатегории',
                'verbose_name_plural': 'Под подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Luk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото одежды')),
                ('size', models.CharField(max_length=40, verbose_name='Размеры')),
                ('percent', models.CharField(max_length=20, verbose_name='Процент')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('min_price', models.IntegerField(default=0, verbose_name='Цена с скидкой')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество покупок')),
                ('composition', models.CharField(max_length=200, verbose_name='Состав')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('country', models.CharField(max_length=255, verbose_name='Страна производителя')),
                ('age', models.CharField(max_length=255, verbose_name='Возрастная группа (лет)')),
                ('sex', models.CharField(max_length=255, verbose_name='Пол')),
                ('equipment', models.CharField(max_length=255, verbose_name='Комплектация')),
                ('season', models.CharField(max_length=255, verbose_name='Сезон')),
                ('appointment', models.CharField(max_length=300, verbose_name='Назначение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='magaz.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorys', to='magaz.subcategory')),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='magaz.subsubcategories')),
            ],
            options={
                'verbose_name': 'Лук',
                'verbose_name_plural': 'Лук',
            },
        ),
    ]
