# Generated by Django 3.1.5 on 2021-01-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luk',
            name='percent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах'),
        ),
    ]
