# Generated by Django 3.1.5 on 2021-01-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0002_auto_20210129_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luk',
            name='min_price',
        ),
    ]
